// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvi_upNi5fzbi1wIg9pOLyVK2zZui9xjQ',
    appId: '1:98129596232:web:666563476a36c3c3af2d7d',
    messagingSenderId: '98129596232',
    projectId: 'tren-boong-concept',
    authDomain: 'tren-boong-concept.firebaseapp.com',
    storageBucket: 'tren-boong-concept.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4bz8VUzpnr8Orsm8VONZZ7uIGp22KFc',
    appId: '1:98129596232:android:89fcd9b638e1e3aeaf2d7d',
    messagingSenderId: '98129596232',
    projectId: 'tren-boong-concept',
    storageBucket: 'tren-boong-concept.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD-Vw58FJU4H4QHANirkgLa-XXiMWsJ5A',
    appId: '1:98129596232:ios:7b4c6def55201f06af2d7d',
    messagingSenderId: '98129596232',
    projectId: 'tren-boong-concept',
    storageBucket: 'tren-boong-concept.appspot.com',
    androidClientId: '98129596232-ff7206u771t7tedheb22cks30cc0fg06.apps.googleusercontent.com',
    iosClientId: '98129596232-6eefptrqoodsbuf899bvkj27c2p00snn.apps.googleusercontent.com',
    iosBundleId: 'micro7.trenBoongConcept',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD-Vw58FJU4H4QHANirkgLa-XXiMWsJ5A',
    appId: '1:98129596232:ios:7b4c6def55201f06af2d7d',
    messagingSenderId: '98129596232',
    projectId: 'tren-boong-concept',
    storageBucket: 'tren-boong-concept.appspot.com',
    androidClientId: '98129596232-ff7206u771t7tedheb22cks30cc0fg06.apps.googleusercontent.com',
    iosClientId: '98129596232-6eefptrqoodsbuf899bvkj27c2p00snn.apps.googleusercontent.com',
    iosBundleId: 'micro7.trenBoongConcept',
  );
}
